accent = "#f0d090"
cursor = "#f0d090"
foreground = "#d4d4d4"
background = "#0f1419"
selection_foreground = "#0f1419"
selection_background = "#f0d090"

color0 = "#1a1f29"
color1 = "#d45a4a"
color2 = "#7a9b76"
color3 = "#d9b768"
color4 = "#5c7a8c"
color5 = "#8c6a7a"
color6 = "#6b9199"
color7 = "#c4c4c4"
color8 = "#3d4552"
color9 = "#e67a6a"
color10 = "#8fb388"
color11 = "#f0d090"
color12 = "#7a94a8"
color13 = "#a6849a"
color14 = "#88b3bd"
color15 = "#e8e8e8"
